import { singleItem } from "./Types";

export const mockItems: singleItem[] = [
  {
    name: "Organic Bananas",
    store: "Whole Foods",
    price: 0.59,
    image: "https://picsum.photos/300/300",
    amount: "6",
    key: "1",
    category: "Fruits",
  },
  {
    name: "Almond Milk",
    store: "Trader Joe's",
    price: 3.49,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "2",
    category: "Dairy",
  },
  {
    name: "Free-Range Eggs",
    store: "Sprouts Farmers Market",
    price: 4.99,
    image: "https://picsum.photos/300/300",
    amount: "12",
    key: "3",
    category: "Produce",
  },
  {
    name: "Whole Grain Bread",
    store: "Wegmans",
    price: 2.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "4",
    category: "Bread",
  },
  {
    name: "Fresh Strawberries",
    store: "Kroger",
    price: 3.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "5",
    category: "Fruits",
  },
  {
    name: "Greek Yogurt",
    store: "Safeway",
    price: 1.29,
    image: "https://picsum.photos/300/300",
    amount: "4",
    key: "6",
    category: "Dairy",
  },
  {
    name: "Baby Spinach",
    store: "Publix",
    price: 2.49,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "7",
    category: "Produce",
  },
  {
    name: "Cheddar Cheese",
    store: "Costco",
    price: 5.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "8",
    category: "Dairy",
  },
  {
    name: "Fresh Salmon Fillet",
    store: "Walmart",
    price: 9.99,
    image: "https://picsum.photos/300/300",
    amount: "2",
    key: "9",
    category: "Seafood",
  },
  {
    name: "Organic Chicken Breast",
    store: "Whole Foods",
    price: 7.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "10",
    category: "Meat",
  },
  {
    name: "Brown Rice",
    store: "Trader Joe's",
    price: 1.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "11",
    category: "Grains",
  },
  {
    name: "Avocado",
    store: "Kroger",
    price: 1.49,
    image: "https://picsum.photos/300/300",
    amount: "2",
    key: "12",
    category: "Fruits",
  },
  {
    name: "Cucumber",
    store: "Safeway",
    price: 0.89,
    image: "https://picsum.photos/300/300",
    amount: "3",
    key: "13",
    category: "Vegetables",
  },
  {
    name: "Tomatoes",
    store: "Publix",
    price: 2.99,
    image: "https://picsum.photos/300/300",
    amount: "4",
    key: "14",
    category: "Vegetables",
  },
  {
    name: "Extra Virgin Olive Oil",
    store: "Costco",
    price: 8.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "15",
    category : "Cooking Oil",
  },
  {
    name: "Peanut Butter",
    store: "Walmart",
    price: 2.49,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "16",
    category: "Spreads",
  },
  {
    name: "Dark Chocolate",
    store: "Trader Joe's",
    price: 2.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "17",
    category: "Candy",
  },
  {
    name: "Red Wine Vinegar",
    store: "Whole Foods",
    price: 3.49,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "18",
    category: "Vinegar",
  },
  {
    name: "Fresh Basil",
    store: "Sprouts Farmers Market",
    price: 1.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "19",
    category: "Herbs",
  },
  {
    name: "Whole Wheat Pasta",
    store: "Kroger",
    price: 1.49,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "20",
    category: "Pasta",
  },

  {
    name: "Broccoli",
    store: "Safeway",
    price: 1.99,
    image: "https://picsum.photos/300/300",
    amount: "1 head",
    key: "32",
    category: "Vegetables",
  },
  {
    name: "Cauliflower",
    store: "Kroger",
    price: 2.49,
    image: "https://picsum.photos/300/300",
    amount: "1 head",
    key: "33",
    category: "Vegetables",
  },
  {
    name: "Bell Peppers",
    store: "Walmart",
    price: 1.29,
    image: "https://picsum.photos/300/300",
    amount: "3 pack",
    key: "34",
    category: "Vegetables",
  },

  // Add household items
  {
    name: "Laundry Detergent",
    store: "Target",
    price: 11.99,
    image: "https://picsum.photos/300/300",
    amount: "100 oz",
    key: "35",
    category: "Household",
  },
  {
    name: "Paper Towels",
    store: "Costco",
    price: 15.99,
    image: "https://picsum.photos/300/300",
    amount: "12 rolls",
    key: "36",
    category: "Household",
  },
  {
    name: "Dish Soap",
    store: "Walmart",
    price: 2.99,
    image: "https://picsum.photos/300/300",
    amount: "24 oz",
    key: "37",
    category: "Household",
  },

  // More cooking oils
  {
    name: "Coconut Oil",
    store: "Trader Joe's",
    price: 6.99,
    image: "https://picsum.photos/300/300",
    amount: "16 oz",
    key: "38",
    category: "Cooking Oil",
  },
  {
    name: "Avocado Oil",
    store: "Whole Foods",
    price: 8.99,
    image: "https://picsum.photos/300/300",
    amount: "16 oz",
    key: "39",
    category: "Cooking Oil",
  },
  {
    name: "Sesame Oil",
    store: "Safeway",
    price: 4.99,
    image: "https://picsum.photos/300/300",
    amount: "8 oz",
    key: "40",
    category: "Cooking Oil",
  },
  {
    name: "Orange Juice",
    store: "Walmart",
    price: 3.29,
    image: "https://picsum.photos/300/300",
    amount: "52 oz",
    key: "29",
    category: "Beverages",
  },
  {
    name: "Coconut Water",
    store: "Trader Joe's",
    price: 2.99,
    image: "https://picsum.photos/300/300",
    amount: "16 oz",
    key: "30",
    category: "Beverages",
  },
  {
    name: "Sparkling Water",
    store: "Target",
    price: 4.99,
    image: "https://picsum.photos/300/300",
    amount: "12 pack",
    key: "31",
    category: "Beverages",
  },
  {
    name: "Honeycrisp Apple",
    store: "Safeway",
    price: 1.29,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "26",
    category: "Fruits",
  },
  {
    name: "Gala Apple",
    store: "Walmart",
    price: 0.89,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "27",
    category: "Fruits",
  },
  {
    name: "Granny Smith Apple",
    store: "Target",
    price: 0.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "28",
    category: "Fruits",
  },
  {
    name: "Green Seedless Grapes",
    store: "Safeway",
    price: 3.99,
    image: "https://picsum.photos/300/300",
    amount: "2 lb",
    key: "21",
    category: "Fruits",
  },
  {
    name: "Red Globe Grapes",
    store: "Trader Joe's",
    price: 4.29,
    image: "https://picsum.photos/300/300",
    amount: "2 lb",
    key: "22",
    category: "Fruits",
  },
  {
    name: "Black Seedless Grapes",
    store: "Walmart",
    price: 3.49,
    image: "https://picsum.photos/300/300",
    amount: "1.5 lb",
    key: "23",
    category: "Fruits",
  },
  {
    name: "Cotton Candy Grapes",
    store: "Whole Foods",
    price: 5.99,
    image: "https://picsum.photos/300/300",
    amount: "1 lb",
    key: "24",
    category: "Fruits",
  },
  {
    name: "Concord Grapes",
    store: "Kroger",
    price: 4.49,
    image: "https://picsum.photos/300/300",
    amount: "2 lb",
    key: "25",
    category: "Fruits",
  },

];
