import { singleItem } from "./Types";

export const mockItems: singleItem[] = [
  {
    name: "Organic Bananas",
    store: "Whole Foods",
    price: 0.59,
    image: "https://picsum.photos/300/300",
    amount: "6",
    key: "1",
  },
  {
    name: "Almond Milk",
    store: "Trader Joe's",
    price: 3.49,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "2",
  },
  {
    name: "Free-Range Eggs",
    store: "Sprouts Farmers Market",
    price: 4.99,
    image: "https://picsum.photos/300/300",
    amount: "12",
    key: "3",
  },
  {
    name: "Whole Grain Bread",
    store: "Wegmans",
    price: 2.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "4",
  },
  {
    name: "Fresh Strawberries",
    store: "Kroger",
    price: 3.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "5",
  },
  {
    name: "Greek Yogurt",
    store: "Safeway",
    price: 1.29,
    image: "https://picsum.photos/300/300",
    amount: "4",
    key: "6",
  },
  {
    name: "Baby Spinach",
    store: "Publix",
    price: 2.49,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "7",
  },
  {
    name: "Cheddar Cheese",
    store: "Costco",
    price: 5.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "8",
  },
  {
    name: "Fresh Salmon Fillet",
    store: "Walmart",
    price: 9.99,
    image: "https://picsum.photos/300/300",
    amount: "2",
    key: "9",
  },
  {
    name: "Organic Chicken Breast",
    store: "Whole Foods",
    price: 7.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "10",
  },
  {
    name: "Brown Rice",
    store: "Trader Joe's",
    price: 1.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "11",
  },
  {
    name: "Avocado",
    store: "Kroger",
    price: 1.49,
    image: "https://picsum.photos/300/300",
    amount: "2",
    key: "12",
  },
  {
    name: "Cucumber",
    store: "Safeway",
    price: 0.89,
    image: "https://picsum.photos/300/300",
    amount: "3",
    key: "13",
  },
  {
    name: "Tomatoes",
    store: "Publix",
    price: 2.99,
    image: "https://picsum.photos/300/300",
    amount: "4",
    key: "14",
  },
  {
    name: "Extra Virgin Olive Oil",
    store: "Costco",
    price: 8.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "15",
  },
  {
    name: "Peanut Butter",
    store: "Walmart",
    price: 2.49,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "16",
  },
  {
    name: "Dark Chocolate",
    store: "Trader Joe's",
    price: 2.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "17",
  },
  {
    name: "Red Wine Vinegar",
    store: "Whole Foods",
    price: 3.49,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "18",
  },
  {
    name: "Fresh Basil",
    store: "Sprouts Farmers Market",
    price: 1.99,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "19",
  },
  {
    name: "Whole Wheat Pasta",
    store: "Kroger",
    price: 1.49,
    image: "https://picsum.photos/300/300",
    amount: "1",
    key: "20",
  },
];
