name: Trigger Scraper

on:
  workflow_dispatch:

# job to run the scraper
jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Completely Remove Old Chrome
        run: |
          sudo apt-get purge -y google-chrome-stable
          sudo rm -rf /usr/bin/google-chrome /usr/local/bin/google-chrome /opt/google/chrome
          sudo rm -rf ~/.cache/google-chrome
          sudo apt-get autoremove -y

      - name: Install Chrome 134+
        run: |
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.35/linux64/chrome-linux64.zip"
          unzip chrome-linux64.zip
          sudo mkdir -p /opt/google/
          sudo mv chrome-linux64 /opt/google/chrome
          sudo ln -sf /opt/google/chrome/chrome /usr/bin/google-chrome
          sudo ln -sf /opt/google/chrome/chrome /usr/local/bin/google-chrome
          google-chrome --version  # Verify installed version

      - name: Install Matching ChromeDriver 134+
        run: |
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.35/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver
          chromedriver --version  # Verify installed version

      - name: Verify Chrome and ChromeDriver Versions
        run: |
          echo "Checking Google Chrome Version..."
          google-chrome --version
          echo "Checking ChromeDriver Version..."
          chromedriver --version

      - name: Run Python Scraper
        run: |
          export CHROME_BINARY_PATH="/opt/google/chrome/chrome"
          export PATH="/usr/local/bin:$PATH"
          echo "Using Chrome from: $CHROME_BINARY_PATH"
          python scraper/__init__.py
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}


